
\begin{cols}
\begin{col}{0.52\textwidth}

\begin{objectivesBox}{iconmonstr-target-4-240.png}
You have learnt to ask a RQ, design a study, classify and summarise the data, and perform some hypothesis tests.
\textbf{In this chapter}, you will learn to:
\begin{itemize}\tightlist
  \item
  identify situations where comparing proportions or odds is appropriate.
  \item
  form confidence intervals for the difference between two proportions.
  \item
  form confidence intervals for odds ratios using software output.
  \item
  conduct hypothesis tests for comparing two proportions, using a $z$-test.
  \item
  conduct hypothesis tests for comparing two odds, using chi-square tests in software output.
  \item
  determine whether the conditions for using these methods apply in a given situation.
\end{itemize}
\end{objectivesBox}

\end{col}

\begin{col}{0.03\textwidth}
~
\end{col}

\begin{col}{0.45\textwidth}
```{r echo=FALSE, fig.width=4.25,fig.height=2.68, out.width="95%"}
SixSteps(5, 
         "CIs and Tests:\nodds or proportions")
```
\end{col}
\end{cols}
