
\begin{cols}
\begin{col}{0.52\textwidth}

\begin{objectivesBox}{iconmonstr-target-4-240.png}
So far, you have learnt about the research process, including analysing data using confidence intervals and conducting hypothesis tests.
\textbf{In this chapter}, you will learn to:
\begin{itemize}\tightlist
  \item
  produce confidence intervals for correlation coefficients.
  \item
  conduct hypothesis tests for correlation coefficients.
  \item
  produce and interpret linear regression equations.
  \item
  conduct hypothesis tests for the slope in a regression line.
  \item
  produce confidence intervals for the slope in a regression line.
  \item
  determine whether the conditions for using these methods apply in a given situation.
\end{itemize}
\end{objectivesBox}

\end{col}

\begin{col}{0.03\textwidth}
~
\end{col}

\begin{col}{0.45\textwidth}
```{r echo=FALSE, fig.width=4.25,fig.height=2.68, out.width="95%"}
SixSteps(5, 
         "Correlation; Regression:\nCIs and tests")

```
\end{col}
\end{cols}
