```{r echo=FALSE, results='hide'}
date.str <- date()
seed <- as.numeric( paste( substr(date.str, 18, 19), # Second
                           substr(date.str, 15, 16),
                           sep = "") # Minutes
                       )
# For Roulette wheel
```

:::::: {.cols data-latex=""}

::: {.col data-latex="{0.55\textwidth}"}
If the wheel is spun (say) $15$ times, the \emph{sample} proportion of odd-spins in those $15$ spins, denoted $\hat{p}$, will vary.
But, \emph{how} does $\hat{p}$ vary from one set of $15$ spins to another set of $15$ spins? 
Can we describe \emph{how} the values of $\hat{p}$ vary?
:::

::: {.col data-latex="{0.07\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as a column separator -->
:::

::: {.col data-latex="{0.35\textwidth}"}

```{r RouletteWheel, echo=FALSE, cache=FALSE, out.width = "80%", fig.align="center", fig.height=2, fig.width=2}
# Wheel  
DD <- 10
dd <- 4

spin <- plotSpinningWheel( angle = deg2rad(360/37)/2, 
                           radius = dd, 
                           wheelSize = c(DD, dd),
                           plotShadow = FALSE,  
                           main = "")
```
:::
::::::



