# (PART) Analysis: confidence intervals {-}



# Introducing confidence intervals {#CIIntro}

Chapter\ \@ref(SamplingVariation) introduced the idea of sampling variation.
In Chaps.\ \@ref(CIOneProportion) to\ \@ref(OddsRatiosCI), this idea is used to form *confidence intervals*.
Confidence intervals answer [estimation-type RQ](#TypesOfRQs), where the precision of a *statistic* to estimate a *parameter* is of interest.
In this Part, answering estimation-type RQs is discussed for:

* Descriptive RQs: 
  * One proportion: Chap.\ \@ref(CIOneProportion), when the variable is qualitative.
  * One mean: Chap.\ \@ref(OneMeanConfInterval), when the variable is quantitative.
  * Mean difference: Chap.\ \@ref(PairedCI), for *paired* quantitative data having a within-individuals comparison.
* Relational or interventional RQs with a between-individuals *comparison*:
  * Comparing means in two groups: Chap.\ \@ref(CITwoMeans), when the response variable is quantitative.
  * Comparing odds in two groups: Chap.\ \@ref(OddsRatiosCI), when the response variable is qualitative.

Answering estimation-type RQs for relational or interventional RQs with a *connection* (i.e., for two quantitative variables) is explored later (Chaps.\ \@ref(Correlation) and\ \@ref(Regression)).
The precision of statistics influences [decision-type RQs](#TypesOfRQs) too: when [statistics](#StatisticsAndParameters) precisely estimate [parameters](#StatisticsAndParameters), making decisions about parameters is easier.

The previous chapters, where tools for describing sampling variation were introduced, are used in this part to understand the precision of statistics.


```{r fig.cap="", fig.align="center", fig.width=3, out.width="35%"}
SixSteps(5, "Comparison RQs: CIs")
```



