# Appendix: Checklists {#Appendix-Checklists}


In this Appendix,
two checklists are provided for evaluating and producing 
graphs (Sect. \@ref(Checklist-Graphics))
and
tables (Sect. \@ref(Checklist-Tables)).
These may not be comprehensive.

## A checklist for good scientific graphics {#Checklist-Graphics}



```{r GraphicsChecklist, echo=FALSE}
GraphicsChecklist <- array( dim=c(8, 3))
colnames(GraphicsChecklist) <- c("", "Criterion", "Details")

GraphicsChecklist[, 1] <- 1:8
GraphicsChecklist[, 2] <- c("Caption",
                            "Simplicity",
                            "Clarity",
                            "Accuracy",
                            "Message",
                            "Scaling",
                            "Organisation",
                            "Units")
GraphicsChecklist[1, 3] <- "Does the graph have a descriptive caption under the graph: comprehensive, clear and accurate (what, where, when)?"
GraphicsChecklist[2, 3] <- "Is the information is presented simply (e.g., not too many messages in one graph)?"
GraphicsChecklist[3, 3] <- "Is  the  information  is  presented clearly (e.g., use visible symbols; colours and symbols explained; no chart junk; no unnecessary 3-D; minimum axis tick marks; faint grid lines if needed)?"
GraphicsChecklist[4, 3] <- "Is the information accurate (e.g., not misleading, complete)?"
GraphicsChecklist[5, 3] <- "Is the main message, theme, trend, or comparison of greatest importance easily seen?"
GraphicsChecklist[6, 3] <- "Are the comparisons made on linear scale (e.g., avoiding comparison of volumes or areas or angles)?"
GraphicsChecklist[7, 3] <- "Are the data are sorted meaningfully to aid interpretation?"
GraphicsChecklist[8, 3] <- "Are the units of measurement given?"

table.cap <- "A checklist for good scientific graphics"

if( knitr::is_latex_output() ) {
  kable(GraphicsChecklist, 
        format="latex",
        longtable=FALSE,
        escape=FALSE,
      col.names=colnames(GraphicsChecklist),
      booktabs=TRUE,
      #linesep = c("\\addlinespace",  # Otherwise addes a space after five lines... 
      #align= c("c", "r", "p{12cm}"),
      caption=table.cap) %>%
    row_spec(0, bold=TRUE) %>%
    kable_styling(font_size=9) %>%
    column_spec(3, width="12cm")
}
if( knitr::is_html_output() ) {
  kable(GraphicsChecklist, 
        format="html",
        longtable=FALSE,
      col.names=colnames(GraphicsChecklist),
      booktabs=TRUE,
      align= c("c", "r", "l"),
      caption=table.cap) %>%
   kable_styling(full_width=FALSE) %>%
    row_spec(0, bold=TRUE) 
}

```




## A checklist for good scientific tables {#Checklist-Tables}



```{r TablesChecklist, echo=FALSE}

TableChecklist <- array( dim=c(9, 3))
colnames(TableChecklist) <- c("", "Criterion", "Details")

TableChecklist[, 1] <- 1:9
TableChecklist[, 2] <- c("Caption",
                         "Clarity",
                         "Numbers",
                         "Alignment",
                         "Arrangement",
                         "Vertical lines",
                         "Horizontal lines",
                         "Units",
                         "Minimalist")
TableChecklist[1, 3] <- "Does the table have a descriptive caption above the table: comprehensive, clear and accurate (what, where, when)?"
TableChecklist[2, 3] <- "Are the row and columns in the table clearly labelled and explained?"
TableChecklist[3, 3] <- "Are a suitable number of decimal places (or significant figures) displayed?"
TableChecklist[4, 3] <- "Are the numbers aligned to allow easy comparison (e.g., on decimal points)?"
TableChecklist[5, 3] <- "Are the table columns/rows meaningfully arranged to emphasise patterns (e.g., not just alphabetically by default)?"
TableChecklist[6, 3] <- "Are there no vertical lines except where absolutely essential?"
TableChecklist[7, 3] <- "Are there a minimum number of horizontal lines?"
TableChecklist[8, 3] <- "Are the units of measurement clearly given?"
TableChecklist[9, 3] <- "Is unnecessary text avoided?"

table.cap <- "A checklist for good scientific tables"

if( knitr::is_latex_output() ) {
  kable(TableChecklist, 
        format="latex",
        longtable=FALSE,
#        escape=FALSE,
      col.names=colnames(TableChecklist),
      booktabs=TRUE,
      #linesep = c("\\addlinespace",  # Otherwise addes a space after five lines... 
      #align= c("c", "r", "p{12cm}"),
      caption=table.cap) %>%
    row_spec(0, bold=TRUE) %>%
    kable_styling(font_size=9) %>%
    column_spec(3, width="12cm")
}
if( knitr::is_html_output() ) {
  kable(TableChecklist, 
        format="html",
        longtable=FALSE,
      col.names=colnames(TableChecklist),
      booktabs=TRUE,
      align= c("c", "r", "l"),
      caption=table.cap) %>%
   kable_styling(full_width=FALSE) %>%
    row_spec(0, bold=TRUE) 
}

```

