# Glossary {#Glossary}

<!-- Add things like boxplot, histogram, error bar chart, etc? -->



[68--95--99.7 rule](#def:EmpiricalRule)
: For *any* bell-shaped distribution, *approximately* 68\% of observations lie within one standard deviation of the mean, 95\% of observations lie within two standard deviations of the mean, and 99.7\% of observations lie within three standard deviations of the mean.
Also called the *empirical rule*.


[Accuracy](#PrecisionAccuracy)
: *Accuracy* refers to how close a *sample* estimate is to the *population* value, on average.


[Alternative hypothesis](#def:AltHypothesis)
: The *alternative hypothesis* proposes that any difference, change or relationship observed in the sample is because a difference, change or relationship exists the *population* (that is, the difference, change or relationship cannot be explained by sampling variation).



[Bell-shaped distributions](#NormalDistributions)
: See *Normal distributions*.


[Bias](#def:Bias)
: *Bias* compromises the results or inferences in a study, which may lead to inaccurate conclusions.
*Bias* can be introduced at any part of the research process, and may occur consciously or unconsciously.


[Blinding](#DescribingBlinding)
: *Blinding* when those involved in the study do not know which comparison group the study individuals are in.  
A study can blind the **researcher** to knowing what comparison group the study individuals are in.  
A study can blind the **participants** to knowing what comparison group they are in.  
A study can blind the **analysts** to knowing what comparison group the individuals are in during analysis.


[Blocking](#def:Blocking)
: *Blocking* is when units of analysis are arranged in groups (called blocks) that are similar to one another. 


[Carryover effect](#def:CarryoverEffect)
: The *carry-over effect* is when the influence of past experience(s) of the individuals carry over to influence future experience(s) of the individuals, for experimental studies (Sect. \@ref(CarryOverEffectExperimental)) or observational studies (Sect. \@ref(CarryOverEffectObservational)).



[Cases](#def:UnitOfAnalysis)
: The individuals units in the population; the [*units of analysis*](#def:UnitOfAnalysis).
Also called *individuals*, or *subjects* when the individuals are people.



[Categorical data](#def:QuantitativeData)
: *Cateogorical data* is not *mathematically* numerical data: it consists of categories or labels (even if those labels are numbers). 
In this book, categorical data is called *qualitative* data.



[Classical approach to probability](#def:ClassicalApproachToProbability)
: In the *classical approach to probability*, the probability of an event occurring is the number of elements of the sample space included in the event, divided by the total number of elements in the sample space, *when all outcomes are equally likely*.



[Cluster sampling](#ClusterSampling)
: A sample where the population is split into a large number of small groups called *clusters*, then a *simple random sample* of clusters is selected and *every* member of the chosen small groups is part of the sample.


[Collusion](#Collusion)
: *Collusion* occurs when people work together to produce a work, but only one gets the credit for it.  
At university, collusion happens if you give or receive help in completing any form of individual assessment such as assignments and exams.



[Comparison](#def:Comparison)
: The *comparison* in the RQ identifies the small number of different, distinct subsets of the population between which the outcome is being compared.
The groups being compared have either *imposed* differences on the individuals, or have *existing* differences in the individuals.


[Conceptual definition](#def:ConceptualDefinition)
: A *conceptual definition* articulates exactly and precisely *what* is being measured, observed or assessed in a study.


[Confidence interval](#def:ConfidenceInterval)
: A *confidence interval* is an interval in which the population [*parameter*](#def:Parameter) is likely to be contained, if we found many samples the same way.  
If we computed the 95\% confidence interval (or CI) from each sample, about 95\% of the CIs would contain the [*statistic*](#def:Statistic) of interest.
This interval is called a *confidence interval*.  
Alternatively, the CI can be seen as the range of plausible values for the [parameter](#def:Parameter) that may have produced the observed sample [statistic](#def:Statistic).
We studied CIs is some specific situations (there are hundreds more!):

* CIs for one proportion: Chap. \@ref(CIOneProportion)
* CIs for one mean: Chap. \@ref(OneMeanConfInterval)
* CIs for a mean difference (*paired* sample mean): Chap. \@ref(PairedCI)
* CIs for the difference between two means: Chap. \@ref(CITwoMeans)
* CIs for comparing two odds: Chap. \@ref(OddsRatiosCI)
* CIs for regression parameters: Sect. \@ref(RegressionCI)


[Confounding](#def:Confounding)
: *Confounding* is when a third variable influences the observed relationship between the response and explanatory variable. 
 
 
[Confounding variable](#def:ConfoundingVariable)
: A *confounding variable* (or a *confounder*) is an extraneous variable associated with the response and explanatory variables.


[Conditions](#def:Conditions)
: The *conditions* of interest that those in the observational study can be exposed to.


[Connection](#def:Connection)
: The *connection* in the RQ identifies another quantity of interest that varies, that may be related to the outcome. 


[Continuous data](#def:ContinuousData)
: *Continuous* quantitative data has (at least in theory) an infinite number of possible values between any two given values. 


[Control](#def:Control)
: A *control* is a unit of analysis without the treatment applied (but as similar as possible in every other way to other units of analysis).


[Convenience sample](#NonRandomSamples)
: A sample where individuals are selected because they are convenient for the researcher.

[Data](#def:Data)
: *Data* refers items of information obtained from a study (such as height of seedlings, or the type of medication given).


[Data set](#def:DataSet)
: A *data set* refers to a collection of data from a study.


[Descriptive study](#def:DescriptiveStudy)
: A *descriptive study* is one where the researchers only focus on collecting, measuring, assessing or describing an outcome in the population. 
 
 
[Discrete data](#def:DiscreteData)
: *Discrete* quantitative data has a countable number of possible values between any two given values of the variable. 
 
 
[Ecological validity](#def:EcologicalValidity)
: A study is *ecologically valid* if the study methods, materials and context approximate the real situation being studied.


[Event](#def:Event)
: An *event* is any combination of the elements in the [sample space](#def:SampleSpace).


[Exclusion criteria](#def:ExclusionCriteria) 
: *Exclusion criteria* are characteristics that disqualify potential individuals from being included in the study.


[Empirical rule](#def:EmpiricalRule)
: For *any* bell-shaped distribution, *approximately* 68\% of observations lie within one standard deviation of the mean, 95\% of observations lie within two standard deviations of the mean, and 99.7\% of observations lie within three standard deviations of the mean.
Also called the *68--95--99.7 rule*.



[Experiment (or Experimental study)](#def:Experiment)
: An *experimental study* (or an *experiment*) has an *intervention*: the researchers *impose* and can *manipulate* the values of the explanatory variable.


 [Experimenter effect](#def:ObserverEffect)
: The *experimenter effect* is another name for *observer bias* in experimental studies (that is, when the researchers are *unintentionally* influenced the subjects).



[Explanatory variable](#def:ExplanatoryVariable)
: An *explanatory variable* is a variable of interest from the individuals in the study which (potentially) causes changes in, or is related to, the response variable. 


[External validity](#def:ExternalValidity)
: *Externally validity* refers to the ability to generalise the results to other groups in the population apart from the sample studied.
For a study to be truly externally valid, the sample must be a random sample from the population.


[Extraneous variable](#def:ExtranaeousVariable)
: An *extraneous* variable is any variable that is (potentially) associated with the response variable, but is not one the explanatory variable. 
 
 

[Extrapolation](#def:Extrapolation)
: *Extrapolation* refers to making prediction outside the range of the available data.
Extrapolation beyond the data can lead to nonsense predictions.



[Fraud](#Fraud)
: *Fraud* refers to the intent to deceive. *Fraud* can occur by:
   
* taking an exam for another student or letting someone take an exam for you
* falsifying or inventing research data and findings
* altering or fabricating information
* forging a document
* falsifying past academic records or employment details in order to gain entrance into the university



[Hawthorne effect](#def:HawthorneEffect)
: The *Hawthorne effect* is the tendency of individuals to change their behaviour if they know (or think) they are being observed, in experimental studies (Sect. \@ref(HawthorneEffectExperimental)) or observational studies (Sect. \@ref(HawthorneEffectObservational)).


Hypothesis
: A *hypothesis* is a possible answer to a (research) question.
More specifically, see *null hypothesis* or *alternative hypothesis*


Hypothesis test
: A *hypothesis test* is a way to formally answer questions about a population, based on information obtained from a sample.
In this book, we have looked at some [specific hypothesis tests](#SelectTest) (hundreds exist:  @kanji2006100!):

* Hypothesis tests about a single mean: Chap. \@ref(TestOneMean)
* Hypothesis tests about a mean difference (means of *paired* samples): Chap. \@ref(TestPairedMeans)
* Hypothesis tests comparing two means: Chap. \@ref(TestTwoMeans)
* Hypothesis tests comparing odds (or percentages): Chap. \@ref(TestsOddsRatio)
* Hypothesis tests about a correlation: Sect. \@ref(CorrelationTesting)
* Hypothesis tests about regression parameters: Sect. \@ref(RegressionHT)


[Inclusion criteria](#def:InclusionCriteria) 
: *Inclusion criteria* are characteristics that individuals must meet explicitly to be included in the study. 
 
 
[Independence](#def:Independence)
: Two events are *independent* if the probability of one event doesn't change depending on whether or not other event has happened.


[Individuals](#def:Population)
: The individuals units in the population from which the observations of interest could be made; the [*units of analysis*](#def:UnitOfAnalysis).
Also called *cases*, or *subjects* when the individuals are people.


[Internal validity](#def:InternalValidity)
: *Internally valid* refers to how reasonable and logical it is to conclude that changes in the value of the response variable can be attributed to changes in the values of the explanatory variable; that is, the strength of the *inferences* made from the study.
A study with *high* internal validity has shown that the changes in the response variable can be attributed to changes in the explanatory variables; other explanations have been ruled out.



 
[Intervention](#def:Intervention)
: An *intervention* is a comparison or connection whose value can be manipulated by the researchers.
That is, the researchers have *imposed* the intervention upon those in the study *intending to change the outcome*.


[IQR](#def:IQR)
: The *IQR* is the range in which the middle 50% of the data lie;
the difference between the third and the first quartiles.


[IQR rule for identifying outliers](#def:IQRRuleForIdentifyingOutliers)
: The IQR rule can identify outliers as either:

* *mild* (observations $1.5\times \text{IQR}$ more unusual than $Q_1$ or $Q_3$), or
* *extreme* (observations $3\times\text{IQR}$ more unusual than $Q_1$ or $Q_3$).


[Judgement sample](#NonRandomSamples)
: A sample where individuals are selected, based on the researchers' judgement, depending on whether the researcher thinks they are likely to be agreeable or helpful.
  

[Levels](#def:Levels) of a qualitative variable
: The *levels* (or the *values*) of a qualitative variable refer to the names of the distinct categories. 



[Lurking variable](#def:LurkingVariable)
: A *lurking variable* is an extraneous variable associated with the response and explanatory variables (that is, is a confounding variable), but whose values are not measured, assessed, described or recorded in the study. 


[Mean](#def:Mean)
: The *mean* is one way to measure the 'average' value of quantitative data.
The *arithmetic mean* can be considered as the 'balance point' of the data, or the value such that the positive and negative distances from the mean add to zero.




[Median](#def:Median)
: The *median* is one way to measure the 'average' value of some data.
The *median* is a value such that half the values are larger than the median, and half the values are smaller than the median.



[Multistage sampling](#MultistageSampling)
: A sample where large groups are selected using a *simple random sample*, then smaller groups within those large groups are selected using a *simple random sample*.
The simple randomly sampling can continue for as many levels as necessary.


[Nominal variable](#Nominal)
: A *nominal* qualitative variable is a qualitative variable where the levels *do not* have a natural order. 


[Normal distribution](#NormalDistributions)
: A *normal distribution* is symmetrical distribution, with most values in the centre of the distribution.
The normal distribution is described by its *mean* and *standard deviation*.
A picture of a normal distribution is shown in Fig. \@ref(fig:DefNormalDistribution).
Normal distributions are also called *bell-shaped* distributions.

```{r DefNormalDistribution, echo=FALSE, fig.cap="A normal distribution", fig.align="center", fig.width=5, fig.height=3}
par( mar = c(4, 1, 1, 1) + 0.1)
zz <- seq(-4, 4,
          length = 100)
yy <- dnorm(zz)

plot( yy ~ zz,
   col = "blue",
   axes = FALSE,
   type = "l",
   xlab = expression(italic(z)-score),
   ylab = "",
   lwd = 2)
axis(side = 1)
abline(h = 0,
       col = "grey")
abline(v = 0,
       col = "grey")
```


[Null hypothesis](#def:NullHypothesis)
: The *null hypothesis* proposes that any difference, change or relationship observed in the sample can be explained by sampling variation (that is, no difference, change or relationship exists the *population*).


[Observational study](#def:ObservationalStudy)
: An *observational study* is one where the researchers *do not impose*, and *cannot manipulate*, the comparison or connection upon those in the study to (potentially) change the response of the participants.


[Observer effect](#def:ObserverEffect)
: The *observer effect* occurs when the researchers (unconsciously) change their behaviour to conform to expectations because they know what values of the explanatory variable apply to the individuals.
This may cause the *individuals* to change their behaviour or reporting also.




[Odds](#def:Odds)
: The *odds* of some event is the proportion (or percentage, or number) of times that an event happens, divided by the proportion (or percentage, or number) of times that the event does *not* happen.


[Odds ratio](#def:OddsRatio)
: The *odds ratio* is how many *times* greater the odds of an event are in one group, compared to the odds of the same event in another group.
 

[Operational definition](#def:OperationalDefinition)
: An *operational definition* articulates exactly *how* something will be identified, measured, observed or assessed.


[Ordinal variable](Ordinal)
: An *ordinal* qualitative variable is a qualitative variable where the levels *do* have a natural order. 


[Outcome](#def:Outcome)
: The *outcome* in a RQ is the result, output, consequence or effect of interest in a study, numerically summarising the entire population (or subsets of the population).


 
[$P$-value](#def:Pvalue)
: A $P$-value is the likelihood of observing the sample results (or something even more extreme) over repeated sampling, under the assumption that the null hypothesis about the population is true.



[Parameter](#def:Parameter)
: A *parameter* is a number describing some feature of a population, and is usually estimated by a [statistic](#def:Statistic).



[Paired data](#def:PairedData)
: *Paired data* is when two observations about the same variable are recorded for each unit of analysis. 


[Percentage](#def:Percentage)
: A *percentage* is a [proportion](#def:Proportion), multiplied by 100.
Percentages are numbers between 0% and 100%.



[Percentiles](#def:Percentiles)
: The $p$th percentile of the data is a value separating the smallest $p$% of the data from the rest.


[Placebo](#def:Placebo)
: A *placebo* is a treatment with no intended effect or active ingredient.


[Placebo effect](#def:PlaceboEffect)
: The *placebo effect* is when individuals report perceived or actual effects without having received the treatment or condition, in experimental studies (Sect. \@ref(PlaceboEffectObservational)) or observational studies (Sect. \@ref(PlaceboEffectObservational)).



[Plagiarism](#Plagiarism)
: *Plagiarism* is using other people’s ideas and research to develop new conclusions, or confirm existing conclusion. 
All sources used when writing research should be acknowledged, otherwise you are committing plagiarism.  
Plagiarism can be deliberate or accidental:

* Deliberate---for instance, if a student intentionally copies the work of others and pretends it is their own work.
* Accidental---for instance, if a student has poor notetaking skills or doesn't know how to reference correctly, and they inadvertently present someone else's ideas and words as their own.



[Population](#def:Population)
: The *population* is the group of individuals (or cases, or subjects if the individuals are people) from which the total set of observations of interest could be made, and to which the results will (hopefully) generalise.


[Precision](#PrecisionAccuracy)
: *Precision* refers to how likely it is that the sample values will be similar or close together, and not vary much from sample to sample.



[Proportion](#def:Proportion)
: A *proportion* is a fraction out of a total.
Proportions are numbers between 0 and 1.


[Protocol](#def:Protocol)
: A *protocol* is a predefined procedure detailing the design and implementation of studies, and for data collection. 


[Qualitative data](#def:QuantitativeData)
: *Qualitative data* is not *mathematically* numerical data: it consists of categories or labels (even if those labels are numbers). 
Also called *categorical* data.


[Quantitative data](#def:QualitativeData)
: *Quantitative data* is *mathematically* numerical data: the numbers themselves have numerical meaning, and it makes sense to be able to perform mathematical operation on them.
Most data that are counted or measured will be quantitative. 
Also called *scale data*.


[Quantitative research](#def:QualitativeResearch)
: *Quantitative research* summarises and analyses data using numerical methods, such as producing averages and percentages. 

      
[Quartiles](#def:Quartiles)
: *Quartiles* describe the variation and shape of data:

* The first quartile $Q_1$: A value that separates the smallest 25\% of observations from the largest 75\%.
  The $Q_1$ is like the median of the *smaller* half of the data, halfway between the minimum value and the median.
* The second quartile $Q_2$: A value that separates the smallest 50\% of observations from the largest 50\%.
  (This is the *median*.)
* The third quartile $Q_3$: The value that separates the smallest 75\% of observations from the largest 25\%.
* The $Q_3$ is like the median of the *larger* half of the data, halfway between the median and the maximum value.


[Quasi-experiment](#def:QuasiExperiment)
: In a *quasi-experiment*, the researchers (1) allocate treatments to groups of individuals (i.e., do not allocate the values of the explanatory variable for the individuals), but (2) do not determine who or what is in those groups.



[Random](#def:Random)
: In research and statistics, *random* means "determined completely by chance".


[Range](#def:Range)
: The *range* is the maximum value of a variable minus the minimum value of the variable. 


[Relative frequency approach to probability](#def:RelativeFrequencyApproachToProbability)
: In the *relative frequency approach to probability*, the probability of an event is (approximately) the number of times the outcomes of interest has appeared in the past, divided by the number of 'attempts' in the past.



[Representative samples](#Representative-samples)
: A representative sample is one where the individuals *in* the sample are not likely to be different the individuals *not in* the sample, at least for the variables of interest.



[Response variable](#def:ResponseVariable)
: A *response variable* is the variable used to measure, assess or describe the outcome on each individual in the population. 
 
 
[Sample](#def:Sample)
: A *sample* is a subset of the population of interest which is actually studied, and from which information is collected.


[Sample space](#def:SampleSpace)
: The *sample space* is a list of all possible and distinct results after administering a procedure whose result is unknown beforehand. is a list of the results after administering a procedure whose result is unknown beforehand. 


[Sampling distribution](#def:SamplingDistribution)
: A *sampling distribution* is the distribution of some sample statistic, showing how its value varies from one sample to sample.


[Sampling frame](#def:SamplingFrame)
: The *sampling frame* is a list of all the members of the population (the individuals, or cases, or subjects). 



[Sampling variation](#def:SamplingVariation)
: *Sampling variation* refers to how much a sample estimate (a [*statistic*](#def:Statistic)) is likely to vary from sample to sample, because each sample is different.


[Selection bias](#def:SelectionBias)
: *Selection bias* is the tendency of a sample to over- or under-estimate a population quantity.


[Scale data](#def:QualitativeData)
: *Scale data* is *mathematically* numerical data: the numbers themselves have numerical meaning, and it makes sense to be able to perform mathematical operation on them. 
Most data that are counted or measured will be quantitative. 
In this book, scale data is called *quantitative data*.


[Simple random sample](#def:SamplingSRS)
: A sample where *every* possible sample of the same size has *same* chance of being selected.



[Standard deviation](#def:StandardDeviation)
: The *standard deviation* is, approximately, the average distance that observations are away from the mean.


[Standard deviation rule for identifying outliers](#def:StandardDeviationRuleForIdentifyingOutliers)
: For approximately symmetric distributions, any observation more than three standard deviations from the mean can be considered an outlier.


[Standard error](#def:StandardError)
: A *standard error* is the standard deviation of all possible values of the sample estimate (from samples of a certain size). 
Any quantity estimated from a sample has a standard error.


   
[Stratified sampling](#StratifiedSampling)
: A sample where the population is split into a small number of large (usually homogeneous) groups called *strata*, then cases are selected using a *simple random sample* from *each* stratum.



[Statistic](#def:Statistic)
: A *statistic* is a number describing some feature of a sample (to estimate a population [parameter](#def:Parameter)).



[Statistical validity](#def:StatisticalValidity)
: A result is *statistically valid* if the conditions for the underlying mathematical calculations and assumptions to be approximately correct are met.
Every confidence interval and hypothesis test has statistical validity conditions.


[Subjective approach to probability](#def:SubjectiveApproachToProbability)
: In the *subjective approach to probability*, various factors are incorporated, perhaps subjectively, to determine the probability of an event.



[Subjects](#def:UnitOfAnalysis)
: The individuals units in the population when they are people; the [*units of analysis*](#def:UnitOfAnalysis).
Also called *individuals* or *cases*; however, those two terms do not refer to people.



[Systematic sampling](#SystematicSampling)
: A sample where the first case is *randomly* selected; then, every $n$th individual is selected.


[Treatments](#def:Treatments)
: *Treatments* are the conditions of interest that those in the study can be exposed to (as the explanatory variable). In experiments, treatments are imposed by researchers. 


[True experiment](#def:TrueExperiment)
: In a true experiment, the researchers (1) allocate treatments to groups of individuals   (i.e., allocate the values of the explanatory variable for the individuals), *and* and (2) determine who or what is in those groups.


[Unit of observation](#def:UnitOfObservation)
: The *unit of observation* is the 'who' or 'what' which are observed, from which measurements are taken and data collected.


[Unit of analysis](#def:UnitOfAnalysis)
: The smallest collection of units of observations (and perhaps the units of observations themselves) about which generalizations and conclusions are made; the smallest *independent* 'who' or 'what' for which information is analysed.
Units of analysis should not typically share a common underlying source.
In an **experimental study**, the unit of analysis is the smallest collection of units of observations that can be randomly allocated to separate treatments.


[Unstandardizing formula](#def:UnstandardizingFormula)
: When the $z$-score is known, the *unstandardising formula* determines the corresponding value of the observation $x$.
 


[Values](#def:Levels) of a qualitative variable
: The *levels* (or the *values*) of a qualitative variable refer to the names of the distinct categories. 


[Variable](#def:Variable)
: A *variable* is a single aspect or characteristic associated with each of a group of individuals under consideration, that can vary from individual to individual. 
 
 
[Voluntary response (self-selecting) sample](#NonRandomSamples)
: A sample where individuals participate if they wish to.

 
[$z$-score](#def:zScore)
: A *$z$-score* measure how many standard deviations a value is from the mean.
In symbols:\bigskip
 \[
   z = \frac{x - \mu}{\sigma},
\]
where $x$ is the value, $\mu$ is the mean of the distribution, and $\sigma$ is the standard deviation of the distribution.
 
