
# Preface {-}

This book introduces quantitative research in the scientific and health disciplines.
The whole research process is introduced, from asking a research question to analysis and reporting of the data.
The main focus, however, is the analysis of data.



## Supporting documents {-}

To support this textbook, the following are also available:

* A [Tutorial Book](https://bookdown.org/pkaldunn/SRM-tutorials/); and
* A [Software Support Book](https://bookdown.org/pkaldunn/SRM-software/) with brief instruction for using jamovi and SPSS to perform *most* of the analyses in this book.

These books are both freely available online.



## The datasets used in this book {-}

Almost every dataset used in this book is a real data-set.
Most are provided in the **R** package [**SRMData**](https://CRAN.R-project.org/package=SRMData); also see App. \@ref(AppendixDataSets).


## Statistical software {-}

Most of this book can be read without relying on any specific statistical software.
However, sometimes jamovi [@Software:jamovi] output is shown.

jamovi is **free** to download and use.
While jamovi looks a little like a spreadsheet, underneath it uses the **R** statistical package [@Software:Rsoftware].



<!-- ## How to use this book {-} -->
```{r, child = if (knitr::is_html_output(exclude = "epub")) 'UseHTML-bs4.Rmd'}
```



## Call-outs used on this book {-}

The following call-outs are used in this book:


:::: {.importantBox .important data-latex="{iconmonstr-warning-8-240.png}"}
These chunks highlight common mistakes or warnings, about a particular concept or about using a formula.
:::


::: {.tipBox .tip data-latex="{iconmonstr-info-6-240.png}"}
These chunks offer helpful information.
:::


::: {.softwareBox .software data-latex="{iconmonstr-laptop-4-240.png}"}
These chunks refer to information about using software (jamovi) or a calculator.
:::


::: {.pronounceBox .pronounce data-latex="{iconmonstr-microphone-7-240.png}"}
These chunks indicate how certain symbols and terms are pronounced.
:::


::: {.thinkBox .think data-latex="{iconmonstr-light-bulb-2-240.png}"}
These chunks give you questions to think about.
:::

`r if (knitr::is_html_output()) '<!--'`
::: {.EOCanswerBox .EOCanswer data-latex="{iconmonstr-check-mark-14-240.png}"}
These end-of-chapter chunks provide answers to most question asked during chapters.
:::
`r if (knitr::is_html_output()) '-->'`




## Who can use this book? {-}

The online textbook is **free** for anyone to use.
Although not essential, an email to the author (explaining how the textbook is being used, who is using the textbook, and your thoughts on the textbook) would be appreciated: `pdunn2 <at> usc.edu.au`.


## How this book was made {-}

This book was made using **R** [@Software:Rsoftware], and the **bookdown** package [@Software:Rbookdown], which is based on `r if (knitr::is_latex_output()) {
   '**Markdown**'
} else {
   '[Markdown](https://en.wikipedia.org/wiki/Markdown)'
}` 
syntax, using **knitr** [@package:knitr].
Numerous other **R** packages were used too.
All of this software is *free* and open source.
Other resources used include:

`r if (knitr::is_html_output()) {'* Some online activities are created using **LearningApps.org**, which is free to use.'}`
* Icons are from 
`r if (knitr::is_latex_output()) {
   '**iconmonstr**'
} else {
   '[**iconmonstr**](https://iconmonstr.com/)'
}`, 
and are freely available.
* The images of the cards (e.g., in Sect. \@ref(NeedForDecisionMaking)) are from https://code.google.com/archive/p/vector-playing-cards/, and are in the public domain.
* The images of dice used in, for example, Sect. \@ref(ProbClassical), are from https://pixabay.com/vectors/dice-games-game-six-sided-face-26772/, and are free.

Special thanks to **Dr Amanda Shaker** (La Trobe University), who has advised of numerous issues (with the corrections).
 


## Learning Outcomes {-}

::: {.objectivesBox .objectives data-latex="{iconmonstr-target-4-240.png}"}
In this book, you will learn to:

* Develop quantitative research questions and testable hypotheses.
* Design quantitative studies to answer simple quantitative research questions.
* Select and produce appropriate graphical, numerical and statistical analyses.
* Select, apply and interpret the results of the correct statistical technique to analyse data.
* Comprehend, apply and communicate in the language of research and statistics.
* Demonstrate professional integrity in planning, interpreting and reporting the results of quantitative studies.
:::






## How to cite this book {-}

Peter K. Dunn (2023). *Scientific Research and Methodology: An introduction to quantitative research in science and health*.
https://bookdown.org/pkaldunn/SRM-Textbook


The online version of this book is licensed under the [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/). 
You can purchase a printed copy from CRC Press in 2024.


```{block2, type='flushright', html.tag='p'}
Peter K. Dunn  
Sippy Downs, Australia
```