
```{r echo=FALSE}
# set.seed(110110)
# 
# blueTransparent <- rgb(0, 0, 1, alpha=0.2, maxColorValue = 1)
# 
# xx <- c( rchisq(300, df=2), 7,7,8,7,7,7,8,7,7,6)
# 
# hist( scales::rescale(xx, to=c(0, 5)),
#       xlab="Values", ylab="Number of obs.",
#       main="A: Skewed right",
#       axes=FALSE,
#       col=blueTransparent,
#       las=1)
# axis(side=2, las=1)
# box()
# dev.print(png, filename="ShapeExampleA-Carousel.png", width=5, height=6,  units="in", res=100)
# 
# 
# 
# 
# xx <- c( rchisq(300, df=1), 2, 2, 1, 1, 2, 0, 0)
# xx <- max(xx) - xx
# hist( scales::rescale(xx, to=c(0, 5)),
#       xlab="Values", ylab="Number of obs.",
#       main="B: Skewed left",
#       axes=FALSE,
#       col=blueTransparent,
#       las=1)
# axis(side=2, las=1)
# box()
# dev.print(png, filename="ShapeExampleB-Carousel.png", width=5, height=6,  units="in", res=100)
# 
# 
# 
# 
# xx <- rnorm(500, mean=10)
# hist( scales::rescale(xx, to=c(0, 10)),
#       xlab="Values", ylab="Number of obs.",
#       main="C: Approx. symmetric",
#       axes=FALSE,
#       col=blueTransparent,
#       las=1)
# axis(side=2, las=1)
# box()
# dev.print(png, filename="ShapeExampleC-Carousel.png", width=5, height=6,  units="in", res=100)
# 
# 
# 
# 
# 
# xx1 <- rnorm(500,mean=0, sd=1)
# xx2 <- rnorm(250,mean=4, sd=1)
# xx <- c( xx1[xx1>0], xx2)
# 
# 
# hist( scales::rescale(xx, to=c(0, 10)),
#       right=TRUE,
#       axes=FALSE,
#       col=blueTransparent,
#       las=1,
#       xlab="Values",ylab="Number of obs.",
#       main="D: Bimodal distribution")
# axis(side=2, las=1)
# box()
# dev.print(png, filename="ShapeExampleD-Carousel.png", width=5, height=6,  units="in", res=100)
# 
# 
# 
# 
# xx <- c( rchisq(300, df=18), 7,7,8)
# 
# hist( scales::rescale(xx, to=c(0, 5)),
#       xlab="Values", ylab="Number of obs.",
#       main="E: Slightly skewed right",
#       axes=FALSE,
#       col=blueTransparent,
#       las=1)
# axis(side=2, las=1)
# box()
# dev.print(png, filename="ShapeExampleE-Carousel.png", width=5, height=6,  units="in", res=100)
# 
# 
# 
# 
# 
# xx <- c( rchisq(300, df=18))
# xx <- max(xx) - xx
# hist( scales::rescale(xx, to=c(0, 5)),
#       xlab="Values", ylab="Number of obs.",
#       main="F: Slightly skewed left",
#       axes=FALSE,
#       col=blueTransparent,
#       las=1)
# axis(side=2, las=1)
# box()
# dev.print(png, filename="ShapeExampleF-Carousel.png", width=5, height=6,  units="in", res=100)
# 
# 
# 
# set.seed(4393764) # No reason...
# xx <- runif(1000, -2.5, 2.5)
# hist( scales::rescale(xx, to=c(0, 5)),
#       xlab="Values", ylab="Number of obs.",
#       main="G: Approx. symmetric",
#       axes=FALSE,
#       col=blueTransparent,
#       las=1)
# axis(side=2, las=1)
# box()
# dev.print(png, filename="ShapeExampleG-Carousel.png", width=5, height=6,  units="in", res=100)
# 

```

```{r DescribeShape, echo=FALSE, fig.cap="Some common shapes of the distribution of qualitative data"}
library(slickR)
# https://cran.r-project.org/web/packages/slickR/vignettes/basics.html

ShapePlotsImages <- c(
  "./ShapeExampleA-Carousel.png",
  "./ShapeExampleB-Carousel.png",
  "./ShapeExampleC-Carousel.png",
  "./ShapeExampleD-Carousel.png",
  "./ShapeExampleE-Carousel.png",
  "./ShapeExampleF-Carousel.png",
  "./ShapeExampleG-Carousel.png"
)

opts <-  settings(
         initialSlide=0,
         slidesToShow=2,
         slidesToScroll=1,
         focusOnSelect = TRUE,
         dots=TRUE
       )
slickR(obj = ShapePlotsImages) +
  opts
```
